name: LeezIsland
author: Izmoqwy
version: 1.1.0

depend:
  - LeezCore
main: lz.izmoqwy.island.LeezIsland

commands:
  island:
    aliases: [is]
    description: Island command
  isadmin:
    aliases: [iadmin, islandadmin, isa]
    description: Administrate islands