name: LeezCore
version: 2.0.1-SNAPSHOT
author: Izmoqwy

depend: [Vault]
softdepend: [LiteBans, NametagEdit, FastAsyncWorldEdit, WorldEdit]
main: lz.izmoqwy.core.LeezCore

commands:
  tellraw:
    description: Overrided tellraw command
    permission: minecraft.tellraw
  leezcore:
    aliases: [leez]
    description: Manage low-level LeezSky settings
    permission: leezsky.core.command
permissions:
  leezsky.core.*:
    children:
      leezsky.core.command: true
      leezsky.core.command.reload: false