name: LeezCore
version: 2.1.0
author: Izmoqwy

main: lz.izmoqwy.core.self.LeezCore
depend:
  - Vaulty
softdepend:
  - LiteBans
  - NametagEdit
  - FastAsyncWorldEdit
  - WorldEdit

commands:
  leezcore:
    aliases: [leez]
    description: Manage low-level LeezSky settings
    permission: leezsky.core.command
permissions:
  leezsky.core.*:
    children:
      leezsky.core.command: true
      leezsky.core.command.reload: false