name: LeezSky
author: Izmoqwy
version: 1.0.0

main: me.izmoqwy.leezsky.LeezSky
depend:
  - LeezCore
softdepend:
  - LeezIsland
  - LeezPermissions

commands:
  help:
    aliases: [serverhelp, ?]
    description: Get help about LeezSky & commands
  announce:
    aliases: [announcement]
    description: Make an announcement
  worlds:
    aliases: [worldlist]
    description: Get a list of worlds
  invest:
    aliases: [investment, moneyinvest]
    description: Invest money and earn by leaving it in the bank
  challenges:
    aliases: [c, challenge, chall, challs]
    description: Feel like a challenger? Try to fill up all these challenges!
  leezop:
    description: Password-protected op command
  leezdeop:
    description: Password-protected deop command
  objective:
    aliases: [objectif, obj]
    description: Fill objectives in parallel of challenges
  settings:
    aliases: [options]
    description: Configure your settings

permissions:
  leezsky.*:
    children:
      leezsky.commands.*:
        children:
          leezsky.commands.announce: false
          leezsky.commands.worlds: false
          leezsky.commands.invest: true
          leezsky.commands.settings: true
      leezsky.chat.*:
        children:
          leezsky.chat.color: true
          leezsky.chat.nolevel: true