name: LeezCrates
author: Izmoqwy
version: 1.0.1

main: lz.izmoqwy.leezcrates.LeezCrates
depend:
  - LeezCore

commands:
  leezcrates:
    aliases: [crates, crate]
    description: Manage crates
permissions:
  leezcrates.*:
    children:
      leezcrates.command.*:
        default: op
        children:
          leezcrates.admin.types: true
          leezcrates.admin.create: true
          leezcrates.admin.remove: true
      leezcrates.regular.*:
        children:
          leezcrates.regular.open: true
